### ISSUE TITLE
Crashes on Windows Phone when MSApp.getHtmlPrintDocumentSourceAsync() is called

### ISSUE THREAD

**Issue by jainpiyushb** [Microsoft/Windows-appsample-coloringbook#1]
Tried running the ColoringApp sample project to print a document.
I am using Microsoft Lumia 650 updated to OS Build 10.0.14393.321 Version 1607.

After debugging the app looks like it crashes on MSApp.getHtmlPrintDocumentSourceAsync().
The object conforming to HtmlPrintDocumentSource is returned successfully on the .then block.

Any ideas on what can be the problem ?

**Comment by GrahamDWardle** [comment]
It looks like there is a similar problem with Windows 10. I am not 100% sure but I believe it is the memory stream goes out of scope (and disposed by the using statement ) before the print is finished. Not sure what the best fix is yet.

**Comment by JoshuaPartlow** [comment]
Sorry for the delayed reply. We ended up moving this sample to use the UWP Community Toolkit print helper, which provides a nice interface for managing printing.

**Comment by GrahamDWardle** [comment]
Thank you

Graham D. Wardle
Sent from Mail for Windows 10
