### ISSUE TITLE
Autosave for InkCanvas uisng code-behind

### ISSUE THREAD

**Issue by Javier118** [Microsoft/Windows-appsample-coloringbook#4]
Hello. 
I'm doing an app with IkCanvas using Windows Tempalte Studio and CodeBehind, I want to do autosave to bring a list what you do in InkCanvas and sharing. How can I do it?

**Comment by KarlErickson** [comment]
Hi @Javier118 - you can find code for autosave in the [ColoringPageController.cs](https://github.com/Microsoft/Windows-appsample-coloringbook/blob/master/ColoringBook/Views/ColoringPageController.cs) file. Unfortunately, we don't have the resources to provide more in-depth help, but hopefully this is what you're looking for.
